include: "rules/00_common.smk"
include: "rules/01_merge_vcfs.smk"

##### Target rules #####

rule all:
    input:
###################
# 01_merge_vcfs.smk
###################
## copy_polished_vcfs
#        expand(os.path.join(config["working_dir"], "vcfs/{sample}.vcf"),
#                sample = SAMPLES
#        ),
# merge_vcfs
        os.path.join(config["lts_dir"], "vcfs/merged/all.vcf.gz"),
# extract_loci
        os.path.join(config["lts_dir"], "loci/all.csv")
