include: "rules/00_all.smk"

##### Target rules #####

rule all:
    input:
# index
        os.path.join(config["working_dir"], "vcfs/mikk_no-sibs_line-id.vcf.gz.tbi"),
# nucleotide_divergence
        expand(os.path.join(config["lts_dir"], "nucleotide_divergence/{window_size}.windowed.pi"),
                window_size = config["window_size"]
        )

